name: Deploy to Pages

on:
  push: { branches: main }
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  Deploy-to-Pages:
    name: Deploy to Pages
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@main
        with: { repository: F1248/OpenMacHelper }

      - name: Copy script
        run: |
          /usr/bin/mkdir github-pages
          /usr/bin/cp install.sh _site/index.html

      - name: Configure GitHub Pages
        uses: actions/configure-pages@main

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@main

      - name: Deploy GitHub Pages site
        uses: actions/deploy-pages@main
