name: Deploy to Pages

on:
  push: { branches: main }
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  Deploy-to-Pages:
    name: Deploy to Pages
    runs-on: macos-latest

    permissions:
      pages: write
      id-token: write

    steps:

      - name: Checkout Genius
        uses: actions/checkout@main
        with: 
          repository: F1248/Genius
          path: Genius
          fetch-depth: 0

      - name: Copy Scripts
        run: |
          /bin/mkdir _site
          eval $(
            /opt/homebrew/bin/git -C Genius for-each-ref --format="
              /opt/homebrew/bin/git -C Genius checkout %(refname);
              /bin/cp Genius/install.sh _site/\$(
                /bin/echo %(refname:lstrip=-1) | /usr/bin/sed \"s/^main$/index/\"
              ).html;
            " "refs/remotes/origin/*"
          )

      - name: Configure GitHub Pages
        uses: actions/configure-pages@main

      - name: Attest Build Provenance
        uses: actions/attest-build-provenance@main
        with: { subject-path: _site }

      - name: Upload GitHub Pages Artifact
        uses: actions/upload-pages-artifact@main

      - name: Deploy GitHub Pages Site
        uses: actions/deploy-pages@main
