name: Deploy to Pages

on:
  push: { branches: main }
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  Deploy-to-Pages:
    name: Deploy to Pages
    runs-on: macos-latest

    permissions:
      pages: write
      id-token: write

    steps:

      - name: Checkout
        uses: actions/checkout@main
        with: { repository: F1248/Genius }

      - name: Copy Script
        run: |
          /bin/mkdir _site
          /bin/cp install.sh _site/index.html

      - name: Configure GitHub Pages
        uses: actions/configure-pages@main

      - name: Upload GitHub Pages Artifact
        uses: actions/upload-pages-artifact@main

      - name: Deploy GitHub Pages Site
        uses: actions/deploy-pages@main
