#
# © 2024 F1248 <f1248@mailbox.org>
# See LICENSE.txt for license information.
#

name: Deploy to GitHub Pages

on:
    push:
        paths:
            - .github/workflows/Deploy-to-GitHub-Pages.yml
    workflow_dispatch:

permissions: {}

env:
    GH_TOKEN: ${{ github.token }}

defaults:
    run:
        shell: bash

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    Deploy-to-GitHub-Pages:
        name: Deploy to GitHub Pages
        permissions:
            attestations: write
            id-token: write
            pages: write
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Genius
              uses: actions/checkout@main
              with:
                repository: F1248/Genius
                path: Genius
                fetch-depth: 0

            - name: Copy scripts
              run: |
                cp Genius/Makefile .
                make install-files

            - name: Configure GitHub Pages
              uses: actions/configure-pages@main

            - name: Attest build provenance
              uses: actions/attest-build-provenance@main
              with:
                subject-path: _site

            - name: Upload GitHub Pages artifact
              uses: actions/upload-pages-artifact@main

            - name: Deploy GitHub Pages site
              uses: actions/deploy-pages@main
